### ISSUE TITLE
Incorrect dependency on arraykit and automap

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/static-frame-feedstock#177]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

According to the static-frame requirements.txt (https://github.com/static-frame/static-frame/blob/master/requirements.txt), different versions of static-frame require specific versions of arraykit and automap (although the automap requirement has not changed in a long time).  However, this package has the dependencies as arraykit >=0.2.3 and automap >=0.6.2, which are incorrect.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by flexatone** [comment]
Thanks, @DManowitz , for pointing this out. I will fix this, but in the mean time, you should be able to install everything correctly with pip.

**Comment by DManowitz** [comment]
Note that I forgot about the automap dependency earlier.
